# Fill in the YAML configuration for the microservices 

version: "3.1"
services:
  rabbitMQ_server:
    image: rabbitmq
    container_name: rabbit_mq

  producer:
    build:
      context: .
      dockerfile: Dockerfile_producer
    container_name: producer_flask_container
    ports:
      - "54321:5000"
    depends_on:
      - rabbitMQ_server

  ride_matching_1:
    build:
      context: .
      dockerfile: Dockerfile_ride_matching
    container_name: ride_matching_1
    restart: on-failure
    depends_on:
      - producer
    environment:
      - CONSUMER_ID=Consumer1
      - PRODUCER_ADDRESS=producer:5000

  ride_matching_2:
    build:
      context: .
      dockerfile: Dockerfile_ride_matching
    container_name: ride_matching_2
    restart: on-failure
    depends_on:
      - producer
    environment:
      - CONSUMER_ID=Consumer2
      - PRODUCER_ADDRESS=producer:5000

  ride_database:
    build:
      context: .
      dockerfile: Dockerfile_database
    container_name: ride_database
    restart: on-failure
    depends_on:
      - producer
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb_container
    depends_on:
      - producer
